slogan: "_(:з」∠)_好吧，其实是老黎用来写博客的地方"

menu:
  - title: 归档
    url: archives
    intro: "所有文章"
    icon: "fa fa-archive"
  - title: 分类
    url: categories
    intro: "所有分类"
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "所有标签"
    icon: "fa fa-tags"
  - title: 关于
    url: about
    intro: "博主私♂密档案"
    icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "订阅文章"
    icon: "fa fa-rss"

links:
  - title: "我的Github"
    url: https://github.com/licheetec
    intro: "我的Github帐户"
    icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.ico
duoshuo_shortname: licheetec
google_analytics:

baidu_tongji: true

swiftype_search:
  enable: true
  install_code: M6DvGWx79N2VB16bYVJY
  search_input_selector: st-search-input